// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface CloudflareBindings {
  SLACK_BOT_TOKEN: string;
  NOTION_API_TOKEN: string;
  NOTION_DATABASE_ID: string;
}
