#:schema node_modules/wrangler/config-schema.json
name = "silk-weave"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = [ "nodejs_compat" ]
tail_consumers = [{service = "silk-weave-tail"}]

[observability]
enabled = true

[[queues.producers]]
queue = "silk-weave"
binding = "silk-weave"

[[queues.consumers]]
  queue = "silk-weave"
  max_batch_size = 100
  max_batch_timeout = 30
